tosca_definitions_version: alien_dsl_2_0_0

#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

metadata:
  template_name: org.ystia.kubernetes.pub
  template_version: 2.0.0-SNAPSHOT
  template_author: Ystia

description: Public interface types for Kubernetes support.

imports:
  - tosca-normative-types:1.0.0-ALIEN20

node_types:
  org.ystia.kubernetes.pub.nodes.KubernetesMaster:
    abstract: true
    derived_from: tosca.nodes.SoftwareComponent
    tags:
      icon: /images/kubernetes-master-icon.png
    description: >
      A KubernetesMaster contains Kubernetes services like the API server, the podmaster and so on.
    properties:
      component_version:
        type: version
        required: false
        default: 1.10-stable
        constraints:
          - greater_or_equal: 1.10-stable
    capabilities:
      api_server: org.ystia.kubernetes.pub.capabilities.KubernetesAPIServer
      app_host: org.ystia.kubernetes.pub.capabilities.AppHosting


  org.ystia.kubernetes.pub.nodes.KubernetesWorker:
    abstract: true
    derived_from: tosca.nodes.SoftwareComponent
    tags:
      icon: /images/kubernetes-worker-icon.png
    description: >
      A KubernetesWorker contains Kubernetes services used to run pods.
    properties:
      component_version:
        type: version
        required: false
        default: 1.10-stable
        constraints:
          - greater_or_equal: 1.10-stable
    requirements:
      - api_server:   
          capability: org.ystia.kubernetes.pub.capabilities.KubernetesAPIServer
          node: org.ystia.kubernetes.pub.nodes.KubernetesMaster
          occurrences: [ 1, 1 ]

  org.ystia.kubernetes.pub.nodes.KubernetesApp:
    abstract: true
    derived_from: tosca.nodes.Root
    tags:
      icon: /images/kubernetes-app-icon.png
    properties:
      specs:
        type: list
        description: >
          List of URLs that will be applied in order using 'kubectl apply -f <url>'
        required: true
        entry_schema:
          type: string
    requirements:
      - app_host:
          capability: org.ystia.kubernetes.pub.capabilities.AppHosting
          node: org.ystia.kubernetes.pub.nodes.KubernetesMaster
          relationship: tosca.relationships.HostedOn

capability_types:
  org.ystia.kubernetes.pub.capabilities.KubernetesAPIServer:
    derived_from: tosca.capabilities.Endpoint
    description: >
      A KubernetesAPIServer capability allows to binds to the Kuberntes HTTP API.
    properties:
      port:
        type: integer
        description: The port of the Kubernetes HTTP endpoint.
        required: true
        default: 6443
        constraints:
          - in_range: [ 1, 65535 ]
      
  org.ystia.kubernetes.pub.capabilities.AppHosting:
    derived_from: tosca.capabilities.Container