tosca_definitions_version: alien_dsl_2_0_0

#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

metadata:
  template_name: org.ystia.mongodb.linux.ansible
  template_version: 2.0.0-SNAPSHOT
  template_author: Ystia

description: MongoBD Component

imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - yorc-types:1.0.0
  - org.ystia.common:2.0.0-SNAPSHOT
  - org.ystia.mongodb.pub:2.0.0-SNAPSHOT

node_types:
  org.ystia.mongodb.linux.ansible.nodes.MongoDB:
    derived_from: org.ystia.nodes.DBMS
    description: MongoDB component for linux
    tags:
      icon: /images/mongodb.jpg
    properties:
      component_version:
        type: version
        description: Version of the installed MongoDB component
        default: 3.6
        constraints:
          - valid_values: [3.2,3.4,3.6]
      port:
        type: integer
        description: MongoDB port
        default: 27017
        required: true
      db_path:
        type: string
        description: Path of the database
        default: /var/lib/mongo
        required: true
      quota_enforced:
        type: boolean
        description: Limits each database to a certain number of files
        default: false
        required: true
      quota_maxfiles:
        type: integer
        description: Number of quota files per DB
        default: 8
        required: true
    capabilities:
      host:
        type: org.ystia.mongodb.pub.capabilities.Container.MongoDB
    interfaces:
      Standard:
        create:
          description: MongoDB installation step
          inputs:
            MONGODB_VERSION: { get_property: [SELF, component_version] }
            MONGODB_PORT: { get_property: [SELF, port] }
            MONGODB_DB_PATH: { get_property: [SELF, db_path] }
            MONGODB_QUOTA_ENFORCED { get_property: [SELF, quota_enforced] }
            MONGODB_QUOTA_MAXFILES { get_property: [SELF, quota_maxfiles] }
          implementation: playbooks/mongodb_install.yaml
